[colors.primary]
background = '#11131a'
foreground = '#e1e2eb'
 
[colors.cursor]
text = '#e1e2eb'
cursor = '#c2c6d5' 
 
[colors.vi_mode_cursor]
text = '#11131a'
cursor = '#adc6ff' 
 
[colors.search.matches]
foreground = '#424753' 
background = '#f4aeff' 
 
[colors.search.focused_match]
foreground = '#424753' 
background = '#adc6ff' 
 
[colors.footer_bar]
foreground = '#424753' 
background = '#e1e2eb' 
 
[colors.hints.start]
foreground = '#424753' 
background = '#b1c6f7' 
 
[colors.hints.end]
foreground = '#424753' 
background = '#b1c6f7' 
 
[colors.selection]
text = '#11131a'
background = '#adc6ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#adc6ff' 
yellow = '#005ac1' 
blue = '#adc6ff' 
magenta = '#f4aeff' 
cyan = '#b1c6f7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
